# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Bambuddy"
description: "A self-hosted print archive and management system for Bambu Lab 3D printers."
url: "https://github.com/Cornelicorn/homeassistant-addons/tree/main/bambuddy"
version: "1.0.0"
slug: bambuddy
init: false
panel_icon: mdi:printer-3d
image: "ghcr.io/cornelicorn/homeassistant-addon-bambuddy-{arch}"
arch:
  - aarch64
  - amd64
map:
  - type: ssl
  - type: addon_config
    read_only: false
ports:
  "80/tcp": 8112
ports_description:
  80/tcp: Web interface
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"

# privileged:
#   - NET_RAW
homeassistant_api: true
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem

schema:
  ssl: bool
  certfile: str
  keyfile: str
