# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Spoolman"
description: "Keep track of your inventory of 3D-printer filament spools."
url: "https://github.com/Cornelicorn/homeassistant-addons/tree/main/spoolman"
version: "1.0.1"
slug: spoolman
image: "ghcr.io/cornelicorn/homeassistant-addon-spoolman-{arch}"
arch:
  - aarch64
  - amd64
map:
  - type: addon_config
    read_only: false
    path: /home/app/.local/share/spoolman
ingress: true
ingress_port: 8000
